"""Add order_code to Order model

Revision ID: 6a4753a7aa79
Revises: d0c7ead5fcbb
Create Date: 2025-02-28 01:36:51.668092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4753a7aa79'
down_revision = 'd0c7ead5fcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.String(length=10), nullable=False))
        batch_op.alter_column('payment_method',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=False)
        batch_op.create_unique_constraint("uq_order_order_code", ['order_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint("uq_order_order_code", type_='unique')
        batch_op.alter_column('payment_method',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=True)
        batch_op.drop_column('order_code')
    # ### end Alembic commands ###
